### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by SanzSS** [CSC207-2022F-UofT/course-project-zuck-s-children#48]
Testing is required for all features.

**Comment by HuakunShen** [comment]
This is your CSC207 Office Hour TA, your team member Xi Wang came to office hour today with a unit test question that I couldn't answer right away. I have to solution now for you.

1. Use junit 5 instead of 4
2. use lowercase letters for package names
    https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#naming-conventions

I also sent you an email with more details.

Good luck

**Comment by SanzSS** [comment]
Thank you Huakun!
